// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Testing;
using Microsoft.CodeAnalysis.Testing;
using Xunit;

using Qyl.OpenTelemetry.SemanticConventions.Analyzers;

namespace Qyl.OpenTelemetry.SemanticConventions.Analyzers.Tests;

/// <summary>
/// Loads the Weaver-generated fixture under <c>tests/WeaverRoundTrip/generated/</c>
/// and asserts the analyzer fires the expected diagnostic against it. The fixture
/// is regenerated by <c>tests/WeaverRoundTrip/generate.sh</c> from a pinned Weaver
/// version (see <c>.weaver-version</c>) — CI re-runs the script and diffs against
/// the committed file, so any change in Weaver's default <c>[Obsolete]</c> note
/// format becomes a red build rather than a silent loss of QYL0010 coverage.
/// </summary>
public class WeaverRoundTripTests
{
    [Fact]
    public async Task Weaver_Generated_Deprecated_Attribute_Reports_QYL0010()
    {
        var fixturePath = Path.Combine(
            FindRepoRoot(AppContext.BaseDirectory),
            "tests",
            "WeaverRoundTrip",
            "generated",
            "HttpAttributes.cs");

        Assert.True(File.Exists(fixturePath),
            $"Weaver round-trip fixture missing at {fixturePath}; run tests/WeaverRoundTrip/generate.sh.");

        // The generated file carries an `<auto-generated>` marker, which is correct for
        // Weaver output — but if we concatenated both pieces into a single TestCode string
        // the entire compilation unit would inherit the marker and the analyzer's
        // GeneratedCodeAnalysisFlags.None opt-out would silently swallow every diagnostic.
        // Real consumers always have the generated file in a *separate* source. Mirror that
        // here by feeding the producer and consumer in as two distinct sources.
        var producerSource = File.ReadAllText(fixturePath);
        const string consumerSource = """
            class C
            {
                void M()
                {
                    var x = OpenTelemetry.SemanticConventions.Attributes.HttpAttributes.{|#0:AttributeHttpMethod|};
                }
            }
            """;

        // Weaver's default note format produces the backtick form: "Replaced by `X`."
        // The analyzer surfaces that string verbatim as the second message argument.
        var expected = new DiagnosticResult("QYL0010", DiagnosticSeverity.Warning)
            .WithLocation(0)
            .WithArguments("HttpAttributes.AttributeHttpMethod", "Replaced by `http.request.method`.");

        await new CSharpAnalyzerTest<DeprecatedSemconvAnalyzer, DefaultVerifier>
        {
            TestState =
            {
                Sources =
                {
                    ("HttpAttributes.cs", producerSource),
                    ("Consumer.cs", consumerSource),
                },
                ExpectedDiagnostics = { expected },
            },
        }.RunAsync();
    }

    private static string FindRepoRoot(string start)
    {
        for (var dir = new DirectoryInfo(start); dir is not null; dir = dir.Parent)
        {
            if (File.Exists(Path.Combine(dir.FullName, "Qyl.OpenTelemetry.SemanticConventions.Analyzers.slnx")))
            {
                return dir.FullName;
            }
        }

        throw new InvalidOperationException("Could not find repository root.");
    }
}
