// Copyright The OpenTelemetry Authors
// SPDX-License-Identifier: Apache-2.0

using System.Reflection;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CodeFixes;
using OpenTelemetry.SemanticConventions.Analyzers;

var repoRoot = FindRepoRoot(AppContext.BaseDirectory);
var outputPath = Path.Combine(repoRoot, "docs", "ANcpLua.OpenTelemetry.SemanticConventions.Analyzers.md");
var check = args.Any(arg => string.Equals(arg, "--check", StringComparison.OrdinalIgnoreCase)
    || string.Equals(arg, "check", StringComparison.OrdinalIgnoreCase)
    || string.Equals(arg, "validate", StringComparison.OrdinalIgnoreCase));

var content = GenerateMarkdown(repoRoot);

if (check)
{
    if (!File.Exists(outputPath))
    {
        Console.Error.WriteLine($"Missing generated docs: {outputPath}");
        return 1;
    }

    var existing = File.ReadAllText(outputPath);
    if (!string.Equals(existing, content, StringComparison.Ordinal))
    {
        Console.Error.WriteLine($"Generated docs are stale: {outputPath}");
        return 1;
    }

    Console.WriteLine($"Generated docs are up to date: {Path.GetRelativePath(repoRoot, outputPath)}");
    return 0;
}

Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
File.WriteAllText(outputPath, content);
Console.WriteLine($"Wrote {Path.GetRelativePath(repoRoot, outputPath)}");
return 0;

static string GenerateMarkdown(string repoRoot)
{
    var descriptors = GetDescriptors();
    var fixableIds = GetFixableDiagnosticIds();
    SemconvMigrationCatalog.Validate();
    var entries = SemconvMigrationCatalog.Entries;
    var metadataCount = Count(entries, entry => entry.MigrationKind == SemconvMigrationKind.DeprecatedButGenerated);
    var supplementalCount = Count(entries, SemconvMigrationCatalog.IsSupplementalDiagnosticEntry);
    var exactCount = Count(entries, entry => SemconvMigrationCatalog.IsSupplementalDiagnosticEntry(entry)
        && entry.MigrationKind is SemconvMigrationKind.ExactRename or SemconvMigrationKind.ExactValueRename);
    var manualCount = Count(entries, entry => SemconvMigrationCatalog.IsSupplementalDiagnosticEntry(entry)
        && entry.MigrationKind is SemconvMigrationKind.ContextSensitive or SemconvMigrationKind.ManualReview);
    var removedCount = Count(entries, entry => SemconvMigrationCatalog.IsSupplementalDiagnosticEntry(entry)
        && entry.MigrationKind == SemconvMigrationKind.RemovedNoReplacement);
    var guidanceCount = Count(entries, entry => entry.Kind == SemconvMigrationItemKind.GuidanceOnly);

    var sb = new StringBuilder();
    sb.AppendLine("# ANcpLua.OpenTelemetry.SemanticConventions.Analyzers");
    sb.AppendLine();
    sb.AppendLine("<!-- <auto-generated /> This file is generated by tools/ANcpLua.OpenTelemetry.SemanticConventions.Analyzers.DocsGenerator. -->");
    sb.AppendLine();
    sb.AppendLine("This package analyzes OpenTelemetry semantic-convention usage in C# consumers. The consumer's referenced `OpenTelemetry.SemanticConventions` assembly remains the primary source of truth: rules that read `[Obsolete]` metadata report what that package actually generated. The curated inventory below separates live-metadata coverage from supplemental diagnostics for changelog/model entries that are not reliably visible through live metadata.");
    sb.AppendLine();

    sb.AppendLine("## Diagnostics");
    sb.AppendLine();
    sb.AppendLine("| ID | Severity | Title | Code fix | Description |");
    sb.AppendLine("| -- | -- | -- | -- | -- |");
    foreach (var descriptor in descriptors)
    {
        var codeFix = fixableIds.Contains(descriptor.Id)
            ? descriptor.Id is "OTSC0030" or "OTSC0031" or "OTSC0032"
                ? "Exact replacements only"
                : "Yes"
            : "No";
        sb.Append("| ");
        sb.Append(descriptor.Id);
        sb.Append(" | ");
        sb.Append(descriptor.DefaultSeverity);
        sb.Append(" | ");
        AppendEscapedCell(sb, descriptor.Title.ToString());
        sb.Append(" | ");
        sb.Append(codeFix);
        sb.Append(" | ");
        AppendEscapedCell(sb, descriptor.Description.ToString());
        sb.AppendLine(" |");
    }

    sb.AppendLine();
    sb.AppendLine("## Severity Policy");
    sb.AppendLine();
    sb.AppendLine("- `OTSC0010`, `OTSC0012`, and `OTSC0014` read `[Obsolete]` metadata from the referenced semantic-conventions assembly and keep their descriptor severities.");
    sb.AppendLine("- `OTSC0030` is reserved for production telemetry emission where a supplemental catalog item has an exact one-to-one replacement.");
    sb.AppendLine("- `OTSC0031` is used for context-sensitive migrations, removed/no-replacement entries, guidance-only cases, ambiguous payload dictionaries, and `compatibility` mode downgrades.");
    sb.AppendLine("- `OTSC0032` is used for tests, fixtures, snapshots, migration maps, schema translators, compatibility shims, generated sources, and catalog-like code.");
    sb.AppendLine("- Generated semconv constant libraries may intentionally retain deprecated constants. Their existence is not itself a package bug.");
    sb.AppendLine("- Schema URL translators and code that explicitly emits older schemas are compatibility contexts and should not be escalated to production errors.");

    sb.AppendLine();
    sb.AppendLine("## Configuration");
    sb.AppendLine();
    sb.AppendLine("| Option | Values | Behavior |");
    sb.AppendLine("| -- | -- | -- |");
    sb.AppendLine("| `build_property.OtelSemConvLegacyMode` | `production` (default), `compatibility`, `off` | `production` keeps production errors for exact supplemental migrations. `compatibility` downgrades production supplemental errors to warnings and keeps fixture contexts informational. `off` disables supplemental catalog diagnostics while leaving live `[Obsolete]` metadata rules enabled. |");
    sb.AppendLine("| `build_property.IsTestProject` | `true`, `false` | Test projects downgrade supplemental catalog findings to `OTSC0032` info. Assembly names ending in `.Tests`, paths under `tests/`, and xUnit/NUnit/MSTest attributes are also treated as test context. |");

    sb.AppendLine();
    sb.AppendLine("## Examples");
    sb.AppendLine();
    sb.AppendLine("```csharp");
    sb.AppendLine("activity.SetTag(HttpAttributes.AttributeHttpMethod, \"GET\"); // OTSC0010 from live [Obsolete] metadata.");
    sb.AppendLine("activity.SetTag(\"http.method\", \"GET\");        // OTSC0012 when the referenced SemConv package marks the matching constant [Obsolete].");
    sb.AppendLine("activity.SetTag(\"error.message\", message);      // OTSC0031 because the replacement is domain-specific.");
    sb.AppendLine("tags.Add(\"message.id\", \"42\");                 // OTSC0031 for ambiguous dictionaries until the payload flow is proven.");
    sb.AppendLine("meter.CreateHistogram<long>(\"system.memory.shared\"); // OTSC0030; use \"system.memory.linux.shared\".");
    sb.AppendLine("```");

    sb.AppendLine();
    sb.AppendLine("## Curated Migration Inventory Summary");
    sb.AppendLine();
    sb.AppendLine($"Curated changelog mentions: {entries.Length}. Live metadata rows: {metadataCount}. Supplemental diagnostic rows: {supplementalCount}. Exact supplemental replacements: {exactCount}. Manual/context-sensitive supplemental rows: {manualCount}. Removed/no-replacement supplemental rows: {removedCount}. Guidance-only rows: {guidanceCount}.");
    sb.AppendLine();
    sb.AppendLine("| Version | Domain | Total | Live metadata | Supplemental | Exact supplemental | Manual/context | Removed/no replacement |");
    sb.AppendLine("| -- | -- | --: | --: | --: | --: | --: | --: |");
    foreach (var group in entries
        .GroupBy(entry => (Version: NormalizeVersion(entry.ChangelogVersion, entry.SinceVersion), entry.Domain))
        .OrderByDescending(group => VersionSortKey(group.Key.Version), StringComparer.Ordinal)
        .ThenBy(group => group.Key.Domain, StringComparer.Ordinal))
    {
        var groupEntries = group.ToArray();
        sb.Append("| ");
        sb.Append(group.Key.Version);
        sb.Append(" | ");
        sb.Append(group.Key.Domain);
        sb.Append(" | ");
        sb.Append(groupEntries.Length);
        sb.Append(" | ");
        sb.Append(Count(groupEntries, entry => entry.MigrationKind == SemconvMigrationKind.DeprecatedButGenerated));
        sb.Append(" | ");
        sb.Append(Count(groupEntries, SemconvMigrationCatalog.IsSupplementalDiagnosticEntry));
        sb.Append(" | ");
        sb.Append(Count(groupEntries, entry => SemconvMigrationCatalog.IsSupplementalDiagnosticEntry(entry)
            && entry.MigrationKind is SemconvMigrationKind.ExactRename or SemconvMigrationKind.ExactValueRename));
        sb.Append(" | ");
        sb.Append(Count(groupEntries, entry => SemconvMigrationCatalog.IsSupplementalDiagnosticEntry(entry)
            && entry.MigrationKind is SemconvMigrationKind.ContextSensitive or SemconvMigrationKind.ManualReview));
        sb.Append(" | ");
        sb.Append(Count(groupEntries, entry => SemconvMigrationCatalog.IsSupplementalDiagnosticEntry(entry)
            && entry.MigrationKind == SemconvMigrationKind.RemovedNoReplacement));
        sb.AppendLine(" |");
    }

    sb.AppendLine();
    sb.AppendLine("## Curated Migration Inventory");
    sb.AppendLine();
    sb.AppendLine("| Old name | Kind | Signal | Domain | Since | Migration | Replacement | Evidence |");
    sb.AppendLine("| -- | -- | -- | -- | -- | -- | -- | -- |");
    foreach (var entry in entries
        .OrderBy(entry => entry.Domain, StringComparer.Ordinal)
        .ThenBy(entry => entry.OldName, StringComparer.Ordinal))
    {
        sb.Append("| `");
        sb.Append(entry.OldName);
        sb.Append("` | ");
        sb.Append(entry.Kind);
        sb.Append(" | ");
        sb.Append(entry.Signal);
        sb.Append(" | ");
        sb.Append(entry.Domain);
        sb.Append(" | ");
        AppendEscapedCell(sb, string.IsNullOrEmpty(entry.SinceVersion) ? "-" : entry.SinceVersion);
        sb.Append(" | ");
        sb.Append(entry.MigrationKind);
        sb.Append(" | ");
        AppendEscapedCell(sb, entry.ReplacementNames.Length == 0 ? "-" : string.Join(", ", entry.ReplacementNames.Select(name => "`" + name + "`")));
        sb.Append(" | ");
        AppendEscapedCell(sb, entry.ChangelogEvidence);
        sb.AppendLine(" |");
    }

    sb.AppendLine();
    sb.AppendLine("## Generated File");
    sb.AppendLine();
    sb.AppendLine("Regenerate with:");
    sb.AppendLine();
    sb.AppendLine("```bash");
    sb.AppendLine("dotnet run -c Release --project tools/ANcpLua.OpenTelemetry.SemanticConventions.Analyzers.DocsGenerator");
    sb.AppendLine("dotnet run -c Release --project tools/ANcpLua.OpenTelemetry.SemanticConventions.Analyzers.DocsGenerator -- --check");
    sb.AppendLine("```");
    sb.AppendLine();
    sb.AppendLine("The `--check` mode fails if the generated markdown differs from the checked-in file.");

    return sb.ToString().ReplaceLineEndings("\n");
}

static IReadOnlyList<DiagnosticDescriptor> GetDescriptors() =>
    typeof(DiagnosticDescriptors)
        .GetFields(BindingFlags.Public | BindingFlags.Static)
        .Where(field => field.FieldType == typeof(DiagnosticDescriptor))
        .Select(field => (DiagnosticDescriptor)field.GetValue(null)!)
        .OrderBy(descriptor => descriptor.Id, StringComparer.Ordinal)
        .ToArray();

static HashSet<string> GetFixableDiagnosticIds()
{
    var ids = new HashSet<string>(StringComparer.Ordinal);
    foreach (var type in typeof(DiagnosticDescriptors).Assembly.GetTypes())
    {
        if (type.IsAbstract || !typeof(CodeFixProvider).IsAssignableFrom(type))
        {
            continue;
        }

        CodeFixProvider? provider = null;
        try
        {
            provider = (CodeFixProvider?)Activator.CreateInstance(type);
        }
        catch
        {
            continue;
        }

        if (provider is null)
        {
            continue;
        }

        foreach (var id in provider.FixableDiagnosticIds)
        {
            if (id.StartsWith("OTSC", StringComparison.Ordinal))
            {
                ids.Add(id);
            }
        }
    }

    return ids;
}

static string FindRepoRoot(string start)
{
    var current = new DirectoryInfo(start);
    while (current is not null)
    {
        if (File.Exists(Path.Combine(current.FullName, "ANcpLua.OpenTelemetry.SemanticConventions.Analyzers.slnx")))
        {
            return current.FullName;
        }

        current = current.Parent;
    }

    throw new InvalidOperationException("Could not find repository root.");
}

static int Count<T>(IEnumerable<T> values, Func<T, bool> predicate)
{
    var count = 0;
    foreach (var value in values)
    {
        if (predicate(value))
        {
            count++;
        }
    }

    return count;
}

static string NormalizeVersion(string changelogVersion, string sinceVersion)
{
    if (!string.IsNullOrWhiteSpace(changelogVersion))
    {
        return changelogVersion;
    }

    return string.IsNullOrWhiteSpace(sinceVersion) ? "unspecified" : sinceVersion;
}

static string VersionSortKey(string version) =>
    version is "unspecified" or "unknown" ? "0.0.0" : version;

static void AppendEscapedCell(StringBuilder sb, string value)
{
    sb.Append(value.Replace("\r", " ", StringComparison.Ordinal)
        .Replace("\n", " ", StringComparison.Ordinal)
        .Replace("|", "\\|", StringComparison.Ordinal));
}
